# Generated by Django 5.0.7 on 2024-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companya_foalyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cilent_soni', models.IntegerField()),
                ('qilingan_project_soni', models.IntegerField()),
                ('ish_foalayti', models.IntegerField()),
                ('buyurt_malar', models.IntegerField()),
            ],
        ),
    ]
