# Generated by Django 5.0.7 on 2024-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companya_foalyati',
            name='cilent_soni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companya_foalyati',
            name='ish_foalayti',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companya_foalyati',
            name='qilingan_project_soni',
            field=models.CharField(max_length=255),
        ),
    ]
