# Generated by Django 5.0.7 on 2024-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0002_alter_companya_foalyati_cilent_soni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companya_tarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('content', models.TextField()),
                ('asoschi', models.TextField(blank=True)),
            ],
        ),
    ]
