# Generated by Django 5.0.7 on 2024-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0003_companya_tarixi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companya_tarixi',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
