# Generated by Django 5.0.7 on 2024-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0004_alter_companya_tarixi_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='companya_tarixi',
            name='companiya_disigner',
            field=models.CharField(default='Noma’lum', max_length=255),
        ),
    ]
