# Generated by Django 5.0.7 on 2024-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0005_companya_tarixi_companiya_disigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murtojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('kompanyia_name', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('murojat', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companya_tarixi',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
