# Generated by Django 5.0.7 on 2024-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtxonapp', '0007_murtojat_kompaniy_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murtojat',
            name='telefon',
            field=models.CharField(max_length=13),
        ),
    ]
